### ISSUE TITLE
Default config gets lost during installation

### ISSUE THREAD

**Issue by rgiessmann** [CovertLab/vivarium-ecoli#199]
Hi there,

with a fresh install, the ecoli_master_sim threw: 

```
(wcm) r.giessmann@debian:~/git/vivarium-ecoli$ python ecoli/experiments/ecoli_master_sim.py -h
Traceback (most recent call last):
  File "ecoli/experiments/ecoli_master_sim.py", line 24, in <module>
    import ecoli.composites.ecoli_nonpartition
  File "/home/r.giessmann/miniconda3/envs/wcm/lib/python3.8/site-packages/vivarium_ecoli-0.0.1-py3.8-linux-x86_64.egg/ecoli/composites/ecoli_nonpartition.py", line 28, in <module>
    from ecoli.composites.ecoli_configs import (
  File "/home/r.giessmann/miniconda3/envs/wcm/lib/python3.8/site-packages/vivarium_ecoli-0.0.1-py3.8-linux-x86_64.egg/ecoli/composites/ecoli_configs/__init__.py", line 13, in <module>
    with open(os.path.join(CONFIG_DIR_PATH, 'default.json')) as default_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/r.giessmann/miniconda3/envs/wcm/lib/python3.8/site-packages/vivarium_ecoli-0.0.1-py3.8-linux-x86_64.egg/ecoli/composites/ecoli_configs/default.json'

(wcm) r.giessmann@debian:~/git/vivarium-ecoli$ ls /home/r.giessmann/miniconda3/envs/wcm/lib/python3.8/site-packages/vivarium_ecoli-0.0.1-py3.8-linux-x86_64.egg/ecoli/composites/ecoli_configs/__
__init__.py  __pycache__/ 

(wcm) r.giessmann@debian:~/git/vivarium-ecoli$ ls ecoli/composites/ecoli_configs/
antibiotics_ampicillin.json    cell_wall_test_rig.json  fba_redux_div.json         lysis_initiation.json  reduced_murein.json  test_config.json
antibiotics.json               cloud.json               fba_redux.json             lysis.json             shape.json           test_configs
antibiotics_tetracycline.json  default.json             generate_save_states.json  lysis_trigger.json     silent_unique.json
cell_wall.json                 fba_gd_swap.json         __init__.py                no_partition.json      spatial.json
``` 

... the files didn't get copied during installation. 

My quick fix was:

`(wcm) r.giessmann@debian:~/git/vivarium-ecoli$ cp ecoli/composites/ecoli_configs/default.json /home/r.giessmann/miniconda3/envs/wcm/lib/python3.8/site-packages/vivarium_ecoli-0.0.1-py3.8-linux-x86_64.egg/ecoli/composites/ecoli_configs/`

Worked afterwards. 

I am not sure where you would prefer to have the configs copied in the installation process, so I'm opening just an issue, not a PR.

Let me know if you need anything from my side regarding debugging. 

Thanks in advance! :)

**Comment by thalassemia** [comment]
I've updated the README with new installation instructions that should fix this issue.
